#!/bin/sh
set -e

export PATH="/opt/mxe/usr/bin/:$PATH"

BUILD="$(pwd)"

case "$PKG_CONFIG_PATH" in
  '')
    export PKG_CONFIG_PATH="$BUILD/build_libs/lib/pkgconfig"
    ;;
  *)
    export PKG_CONFIG_PATH="$BUILD/build_libs/lib/pkgconfig:$PKG_CONFIG_PATH"
    ;;
esac

cd "$BUILD"/mpv
DEST_OS=win32 TARGET=x86_64-w64-mingw32.static ./waf configure --lua=luajit --disable-optimize
CFLAGS="-g2 -O0" ./waf build $@