#!/bin/sh
export PATH="/opt/mxe/usr/bin/:$PATH"

DEST_OS=win32 TARGET=x86_64-w64-mingw32.static ./scripts/mpv-config
CFLAGS="-g2 -O0" ./scripts/mpv-build

if [ -z "$1" ] && [ -d "$1" ]; then
    cp -fr mpv/build/mpv.exe "$1"
    cp -fr mpv/build/mpv.com "$1"
fi